# Generated by Django 4.1.3 on 2023-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
            ],
        ),
    ]
