# Generated by Django 4.1.3 on 2023-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='info_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='detail',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='link',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones_notificacion',
        ),
    ]
