# Generated by Django 4.1.3 on 2023-03-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_options_notificacion_info_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='info_message',
        ),
    ]
