# Generated by Django 4.1.3 on 2022-12-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonos', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('otro', models.TextField()),
                ('horarios', models.CharField(blank=True, max_length=100, null=True)),
                ('personas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('coordenadas', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacio',
            },
        ),
        migrations.CreateModel(
            name='Reparticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'reparticion',
                'verbose_name_plural': 'reparciones',
                'db_table': 'reparticion',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sede',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='null', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Uso',
                'verbose_name_plural': 'Usos',
                'db_table': 'uso',
            },
        ),
        migrations.CreateModel(
            name='SedeRaparticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparticion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.reparticion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='ReparticionEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.contacto')),
                ('espacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.espacio')),
                ('reparticion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.reparticion')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.servicio')),
                ('uso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.uso')),
            ],
        ),
    ]
