# Generated by Django 4.1.3 on 2023-05-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cat', models.IntegerField(blank=True, null=True)),
                ('tipo_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_cat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dep', models.IntegerField(blank=True, null=True)),
                ('nom_dep', models.CharField(max_length=50)),
                ('id_acceso', models.IntegerField(blank=True, null=True)),
                ('id_edif', models.IntegerField(blank=True, null=True)),
                ('id_dire', models.IntegerField(blank=True, null=True)),
                ('id_ciud', models.IntegerField(blank=True, null=True)),
                ('longitud', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='ubicaciones.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_espc', models.IntegerField(blank=True, null=True)),
                ('nom_espc', models.CharField(blank=True, max_length=50, null=True)),
                ('id_esp', models.IntegerField(blank=True, null=True)),
                ('id_func', models.IntegerField(blank=True, null=True)),
                ('id_usab', models.IntegerField(blank=True, null=True)),
                ('id_usua', models.IntegerField(blank=True, null=True)),
                ('id_nivel', models.IntegerField(blank=True, null=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='ubicaciones.dependencia')),
            ],
        ),
    ]
