# Generated by Django 4.1.3 on 2022-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='reparticion',
        ),
        migrations.AddField(
            model_name='reparticionespacio',
            name='reparticion_sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ubicaciones.sederaparticion'),
        ),
    ]
