# Generated by Django 4.1.3 on 2022-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0002_remove_reparticionespacio_reparticion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacio',
            options={'verbose_name': 'Espacios', 'verbose_name_plural': 'Espacios'},
        ),
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='uso',
        ),
        migrations.AddField(
            model_name='espacio',
            name='uso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Uso',
        ),
    ]
