# Generated by Django 4.1.3 on 2022-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0007_dias_diasemana_delete_horario_dias_dias_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias',
            name='estado',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
