# Generated by Django 4.1.3 on 2022-12-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0008_dias_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasemamna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.diasemana')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.AddField(
            model_name='diashoras',
            name='horas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.horas'),
        ),
        migrations.AddField(
            model_name='diashoras',
            name='reparticionEspacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.reparticionespacio'),
        ),
        migrations.AddField(
            model_name='reparticionespacio',
            name='diahoras',
            field=models.ManyToManyField(blank=True, through='ubicaciones.DiasHoras', to='ubicaciones.diasemana'),
        ),
    ]
