# Generated by Django 4.1.3 on 2022-12-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0009_diashoras_horas_delete_dias_diashoras_horas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(blank=True, max_length=100, null=True)),
                ('diasemamna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.diasemana')),
                ('reparticionEspacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.reparticionespacio')),
            ],
        ),
        migrations.DeleteModel(
            name='DiasHoras',
        ),
        migrations.DeleteModel(
            name='Horas',
        ),
        migrations.AlterField(
            model_name='reparticionespacio',
            name='diahoras',
            field=models.ManyToManyField(blank=True, through='ubicaciones.DiasHora', to='ubicaciones.diasemana'),
        ),
    ]
