# Generated by Django 4.1.3 on 2022-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0010_diashora_delete_diashoras_delete_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Imagen URL'),
        ),
    ]
