# Generated by Django 4.1.3 on 2022-12-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0011_alter_espacio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sederaparticion',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.contacto'),
        ),
        migrations.AddField(
            model_name='sederaparticion',
            name='diahoras',
            field=models.ManyToManyField(blank=True, through='ubicaciones.DiasHora', to='ubicaciones.diasemana'),
        ),
        migrations.AddField(
            model_name='sederaparticion',
            name='espacio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.espacio'),
        ),
        migrations.AddField(
            model_name='sederaparticion',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.servicio'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='personas',
            field=models.TextField(help_text='Personas (nombre,cargo, email,fonos)'),
        ),
        migrations.AlterField(
            model_name='diashora',
            name='reparticionEspacio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.sederaparticion'),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='coordenadas',
            field=models.CharField(help_text='Coordenadas (Longitud , Latitud)', max_length=250),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='imagen',
            field=models.CharField(blank=True, help_text='Imagen URL', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sederaparticion',
            name='reparticion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.reparticion'),
        ),
        migrations.AlterField(
            model_name='sederaparticion',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubicaciones.sede'),
        ),
        migrations.DeleteModel(
            name='ReparticionEspacio',
        ),
    ]
