# Generated by Django 4.1.3 on 2022-12-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0012_sederaparticion_contacto_sederaparticion_diahoras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sederaparticion',
            options={'verbose_name': 'Formulario de Ingreso'},
        ),
    ]
