# Generated by Django 4.1.3 on 2023-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0014_ciudad_sederaparticion_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cat', models.IntegerField(blank=True, null=True)),
                ('tipo_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_cat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dep', models.IntegerField(blank=True, null=True)),
                ('nom_dep', models.CharField(max_length=50)),
                ('id_acceso', models.IntegerField(blank=True, null=True)),
                ('id_edif', models.IntegerField(blank=True, null=True)),
                ('id_sede', models.IntegerField(blank=True, null=True)),
                ('id_dire', models.IntegerField(blank=True, null=True)),
                ('id_ciud', models.IntegerField(blank=True, null=True)),
                ('longitud', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='diashora',
            name='diasemamna',
        ),
        migrations.RemoveField(
            model_name='diashora',
            name='reparticionEspacio',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='diahoras',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='reparticion',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='servicio',
        ),
        migrations.AlterModelOptions(
            name='espacio',
            options={},
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='uso',
        ),
        migrations.AddField(
            model_name='espacio',
            name='id_esp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='id_espc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='id_func',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='id_nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='id_usab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='id_usua',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='nom_espc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='espacio',
            table=None,
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='DiaSemana',
        ),
        migrations.DeleteModel(
            name='DiasHora',
        ),
        migrations.DeleteModel(
            name='Reparticion',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='SedeRaparticion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
