# Generated by Django 4.1.3 on 2022-12-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_frecuentes', '0004_contacto_espacio_reparticion_sede_servicio_uso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='reparticion',
        ),
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='reparticionespacio',
            name='uso',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='reparticion',
        ),
        migrations.RemoveField(
            model_name='sederaparticion',
            name='sede',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Espacio',
        ),
        migrations.DeleteModel(
            name='Reparticion',
        ),
        migrations.DeleteModel(
            name='ReparticionEspacio',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='SedeRaparticion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Uso',
        ),
    ]
