# Generated by Django 4.1.3 on 2023-05-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_frecuentes', '0005_remove_reparticionespacio_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_frecuentes.categoria'),
        ),
    ]
